export const QUERY_KEY = {
    EMPLOYEE: "EMPLOYEE",
    PROJECT: "PROJECT",
    MANAGER: "MANAGER",
    EMPLOYEE_TOTAL: "EMPLOYEE_TOTAL",
    PROJECT_TOTAL: "PROJECT_TOTAL",
    NOPAGINATE: "NOPAGINATE",
  };